server:
  port: ${PORT:${SERVER_PORT:0}}

#idRandom: ${random.value}

spring:
  application:
    name: api-catalog

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.int}

management:
  endpoints:
    web:
      exposure:
        include: info
  info:
    env:
      enabled: true

info:
  app:
    name: api catalogo
    version: 1.0.0
    description: Catálogo de películas

